"""empty message

Revision ID: 43c83f9f5789
Revises: 
Create Date: 2024-01-29 19:34:37.464833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c83f9f5789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savedrecs',
    sa.Column('Authors', sa.String(length=255), nullable=False),
    sa.Column('Author_Full_Names', sa.String(length=255), nullable=False),
    sa.Column('Article_Title', sa.String(length=255), nullable=False),
    sa.Column('Document_Type', sa.String(length=255), nullable=False),
    sa.Column('Author_Keywords', sa.Text(), nullable=False),
    sa.Column('Keywords_Plus', sa.String(length=255), nullable=False),
    sa.Column('Abstract', sa.Text(), nullable=False),
    sa.Column('Email_Addresses', sa.String(length=255), nullable=False),
    sa.Column('Times_Cited_WoS_Core', sa.String(length=255), nullable=False),
    sa.Column('Times_Cited_All_Databases', sa.String(length=255), nullable=False),
    sa.Column('Publication_Year', sa.DateTime(), nullable=True),
    sa.Column('Volume', sa.Integer(), nullable=True),
    sa.Column('Issue', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Authors', 'Article_Title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('savedrecs')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
